leftnav:
- identifier: ec807d2d-7b66-9ee5-8102-22d6d3d247e8
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: ed6c27f2-3400-fca8-57f8-33a9b3c28471
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: fcb81a42-5863-4cfc-e936-6ec094540c2d
  name: Assignments
  url: /pages/assignments
  weight: 30
